services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: yiski
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  yiski:
    container_name: Yiski
    image: devos-se/yiski-dev:latest
    volumes:
      - ./config.toml:/app/config.toml
      - ./yiski1.config.toml:/app/yiski1.config.toml
#      - ./yiski2.config.toml:/app/yiski2.config.toml
#      - ./yiski3.config.toml:/app/yiski3.config.toml
#      - ./yiski4.config.toml:/app/yiski4.config.toml
      - ./yiski5.config.toml:/app/yiski5.config.toml
#      - ./yiski6.config.toml:/app/yiski6.config.toml

volumes:
  postgres: