services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  yiski:
    container_name: Yiski
    image: devos-se/yiski-dev:latest
    volumes:
      - ./config.toml:/app/config.toml
      - ./yiski1_config.toml:/app/yiski1_config.toml
#      - ./yiski2_config.toml:/app/yiski2_config.toml
#      - ./yiski3_config.toml:/app/yiski3_config.toml
#      - ./yiski4_config.toml:/app/yiski4_config.toml
      - ./yiski5_config.toml:/app/yiski5_config.toml
#      - ./yiski6_config.toml:/app/yiski6_config.toml