services:
  # For main database related stuff, ie infractions, headcrab, more
  postgres:
    image: postgres:16-alpine
    container_name: yiski-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: yiski
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # For caching related tasks
  cache:
    image: valkey/valkey:8-alpine
    container_name: yiski-cache
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
volumes:
  postgres:
  cache: