[universal]
githubToken = ""
botPrefix = "yk!"

[discord]
botToken = ""
ownerRoleID = ""
ventChannelID = ""

[images]
    [images.static]
    devtools = "assets/images/devtoolsconfig.png"
    ims = "assets/images/dreadfulims.png"
    token = "assets/images/token.png"

[videos]
    antihorny = "assets/videos/antihorny.mp4"
    gasp = "assets/videos/gasp.mp4"
    memoryleak = "assets/videos/memoryleak.mp4"
    rtx = "assets/videos/rtx.mp4"
    whatareyoudoing = "assets/videos/whatareyoudoing.mp4"