[metadata]
version = 0

[runner]
mainClass = "one.devos.yiski3.Yiski3"

[module]
configClass = "one.devos.yiski3.Yiski3Config"

[module.packages] # Any sort of information about the module's packages.
databasePackage = "" # Optional, point directly to your Database package if you have database tables.
slashCommandsPackage = "one.devos.yiski3.commands" # Optional, point directly to your Slash Commands package if you have slash commands.

[information]
id = "yiski3"
name = "Yiski3" # Name of your Yiski Module.
description = "Fun and silly commands" # What does your module do? describe that in short detail.
version = "0.1.0" # Optional, what version is your module? This will fallback to the Yiski project version if not supplied.
repo = "https://github.com/devOS-Sanity-Edition/yiski/"
license = "MIT"
authors = [ # List of authors/people that have contributed to the module. At least 1 string is required.
    "asojidev",
    "bluebeargreen"
]
