[metadata]
version = 0

[runner]
mainClass = "one.devos.yiski3.Yiski3"

[module]
configClass = "one.devos.yiski3.Yiski3Config"

[module.packages]
databasePackage = "one.devos.yiski3.tables"

[information]
id = "yiski3"
name = "Yiski3"
description = "Fun and silly commands"
version = "${version}"
repo = "https://github.com/devOS-Sanity-Edition/yiski/"
license = "MIT"
authors = [
    "asojidev",
    "bluebeargreen",
    "CephalonCosmic"
]
