[metadata]
version = 0

[runner]
mainClass = "one.devos.basicmodule.BasicModule"

[module]
configClass = "one.devos.basicmodule.BasicModuleConfig"
    [module.packages]
    databasePackage = "one.devos.basicmodule.database"
    slashCommandsPackage = "one.devos.basicmodule.commands"

[information]
id = "basicmodule"
name = "Basic Module"
description = "A module that just basically exists like your mother"
version = "0.1.0"
repo = "https://github.com/devOS-Sanity-Edition/yiski/tree/aviation/drafts/plugin-loader-metadata/"
license = "MIT"
authors = [
    "asojidev",
    "CephalonCosmic"
]