[images]
    [images.static]
    devtools = "assets/images/devtoolsconfig.png"
    devtoolsfile = "devtoolsconfig.png"
    ims = "assets/images/dreadfulims.png"
    imsfile = "dreadfulims.png"
    token = "assets/images/token.png"
    tokenfile = "token.png"

    [images.gif]
    headcrabsuccess = "assets/images/headcrab_fail.gif"
    headcrabsuccessfile = "headcrab_fail.gif"
    headcrabfail = "assets/images/headcrab_fail.gif"
    headcrabfailfile = "headcrab_fail.gif"

[videos]
antihorny = "assets/videos/antihorny.mp4"
antihornyfile = "antihorny.mp4"
gasp = "assets/videos/gasp.mp4"
gaspfile = "gasp.mp4"
memoryleak = "assets/videos/memoryleak.mp4"
memoryleakfile = "memoryleak.mp4"
rtx = "assets/videos/rtx.mp4"
rtxfile = "rtx.mp4"
whatareyoudoing = "assets/videos/whatareyoudoing.mp4"
whatareyoudoingfile = "whatareyoudoing.mp4"