[metadata]
version = 0

[runner]
mainClass = "one.devos.yiski5.Yiski5"

[module]
configClass = "one.devos.yiski5.Yiski5Config"

[module.packages]
databasePackage = ""

[information]
id = "yiski5"
name = "Yiski5"
description = "Vent wiping"
version = "${version}"
repo = "https://github.com/devOS-Sanity-Edition/yiski/"
license = "MIT"
authors = [
    "CephalonCosmic"
]
